### ISSUE TITLE
Command failed: /bin/sh: fontcustom: command not found

### ISSUE THREAD

**Issue by madeofpeople** [johanbrook/gulp-fontcustom#3]
Hi, I've been getting some errors recently, not sure whats causing it.
I've had my script work before. 

The gulpfile's supersimple,

```
var gulp = require('gulp'),
    fontcustom = require('gulp-fontcustom');

gulp.task('makeiconfont', function(){
  return gulp.src("./svg/**/*.svg")
  .pipe(fontcustom({
    font_name: 'newIconFont'
  }))
  .pipe(gulp.dest("./output"));
});
```

I've had this script work before, tried removing node_modules and running npm install anew, no dice.

In my understanding error 127 is when /bin/sh cant find something in it's path, but I've never run into this problem with gulp/node before. Any thoughts?

```
[13:13:54] Using gulpfile ~/repos/makesvgfont/gulpfile.js
[13:13:54] Starting 'makeiconfont'...

/Users/madeofpeople/repos/makesvgfont/node_modules/gulp-fontcustom/node_modules/child-process-promise/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Command failed: /bin/sh: fontcustom: command not found
fontcustom compile /Users/madeofpeople/repos/makesvgfont/svg --output ./___tmp___ --font_name newIconFont --force true --no_hash true (exited with error code 127)
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by madeofpeople** [comment]
Had to reinstall the fontcustom gem, after having updated my ruby version via RVM.

https://github.com/FontCustom/fontcustom/#installation
